"""empty message

Revision ID: 0fdd796c88b9
Revises: 7a1bf9c405f5
Create Date: 2021-10-16 19:45:45.430659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fdd796c88b9'
down_revision = '7a1bf9c405f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('price', sa.Integer(), nullable=True))
    op.drop_column('cart', 'hours')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('hours', sa.INTEGER(), nullable=True))
    op.drop_column('cart', 'price')
    # ### end Alembic commands ###
